language: node_js
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
script:
  - npm run test:single
  # I build here because prebuild command in package.json is executed only when a user
  # is installing the package
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
